# Q1

In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By

#Importing requests
import requests

# importing regex
import re
import warnings
warnings.filterwarnings('ignore')

In [2]:
driver=webdriver.Chrome(r'C:\Users\admin\Downloads\chromedriver_win32\chromedriver.exe')

In [3]:
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [4]:
fname=[]
fupload=[]
fviews=[]
fdate=[]

In [9]:
name_1=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[2]")
upload_1=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[3]")
views_1=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[4]")
date_1=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[5]")

for i in name_1:
    fname.append(i.text)
for i in upload_1:
    fupload.append(i.text)
for i in views_1:
    fviews.append(i.text)
for i in date_1:
    fdate.append(i.text)

In [10]:
frank=list(range(1,50))

In [11]:
print(len(fname),len(fupload),len(fviews),len(fdate),len(frank))

49 49 49 49 49

In [12]:
table=pd.DataFrame({})
table['Rank']=frank[:]
table['Video Name']=fname[:]
table['Uploader']=fupload[:]
table['Views(billions)']=fviews[:]
table['Upload Date']=fdate[:]
table

,Rank,Video Name,Uploader,Views(billions),Upload Date
0,1,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,12.3,"June 17, 2016"
1,2,"""Despacito""[7]",Luis Fonsi,8.1,"January 12, 2017"
2,3,"""Johny Johny Yes Papa""[14]",LooLoo Kids,6.59,"October 8, 2016"
3,4,"""Bath Song""[15]",Cocomelon – Nursery Rhymes,5.96,"May 2, 2018"
4,5,"""Shape of You""[16]",Ed Sheeran,5.89,"January 30, 2017"
5,6,"""See You Again""[18]",Wiz Khalifa,5.76,"April 6, 2015"
6,7,"""Phonics Song with Two Words""[23]",ChuChu TV,5.12,"March 6, 2014"
7,8,"""Wheels on the Bus""[24]",Cocomelon – Nursery Rhymes,4.84,"May 24, 2018"
8,9,"""Uptown Funk""[25]",Mark Ronson,4.82,"November 19, 2014"
9,10,"""Learning Colors – Colorful Eggs on a Farm""[26]",Miroshka TV,4.8,"February 27, 2018"
10,11,"""Gangnam Style""[27]",Psy,4.66,"July 15, 2012"
11,12,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,4.52,"January 31, 2012"
12,13,"""Dame Tu Cosita""[33]",El Chombo,4.21,"April 5, 2018"
13,14,"""Sugar""[34]",Maroon 5,3.81,"January 14, 2015"
14,15,"""Roar""[35]",Katy Perry,3.72,"September 5, 2013"
15,16,"""Counting Stars""[36]",OneRepublic,3.71,"May 31, 2013"
16,17,"""Axel F""[37]",Crazy Frog,3.71,"June 16, 2009"
17,18,"""Sorry""[38]",Justin Bieber,3.62,"October 22, 2015"
18,19,"""Thinking Out Loud""[39]",Ed Sheeran,3.54,"October 7, 2014"
19,20,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,3.48,"June 25, 2018"
20,21,"""Waka Waka (This Time for Africa)""[41]",Shakira,3.44,"June 4, 2010"
21,22,"""Dark Horse""[42]",Katy Perry,3.43,"February 20, 2014"
22,23,"""Faded""[43]",Alan Walker,3.39,"December 3, 2015"
23,24,"""Let Her Go""[44]",Passenger,3.37,"July 25, 2012"
24,25,"""Girls Like You""[45]",Maroon 5,3.36,"May 31, 2018"
25,26,"""Perfect""[46]",Ed Sheeran,3.35,"November 9, 2017"
26,27,"""Bailando""[47]",Enrique Iglesias,3.32,"April 11, 2014"
27,28,"""Lean On""[48]",Major Lazer,3.32,"March 22, 2015"
28,29,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,3.29,"January 26, 2018"
29,30,"""Lakdi Ki Kathi""[50]",Jingle Toons,3.26,"June 14, 2018"
30,31,Pinkfong Baby Shark - Kids' Songs & Stories,"7,046,700,000","June 17, 2016","November 2, 2020"
31,32,Luis Fonsi,"2,993,700,000","January 12, 2017","August 4, 2017"
32,33,Wiz Khalifa,"2,894,000,000","April 6, 2015","July 10, 2017"
33,34,Psy,"803,700,000","July 15, 2012","November 24, 2012"
34,35,Justin Bieber,"245,400,000","February 19, 2010","July 16, 2010"
35,36,Lady Gaga,"178,400,000","November 24, 2009","April 14, 2010"
36,37,HDCYT,"128,900,000","May 22, 2007","October 25, 2009"
37,38,Judson Laipply,"118,900,000","April 6, 2006","May 2, 2009"
38,39,RCA Records,"92,600,000","February 27, 2007","July 17, 2008"
39,40,Judson Laipply,"78,400,000","April 6, 2006","March 15, 2008"
40,41,CLARUSBARTEL72,"76,600,000","April 9, 2007","March 1, 2008"
41,42,Judson Laipply,"10,600,000","April 6, 2006","May 19, 2006"
42,43,Smosh,"4,300,000","November 28, 2005","March 12, 2006"
43,44,eggtea,"2,700,000","January 31, 2006","February 18, 2006"
44,45,mugenized,"3,400,000","December 1, 2005","January 21, 2006"
45,46,youtubedude,"2,300,000","December 18, 2005","January 9, 2006"
46,47,Nikesoccer,"255,000","October 21, 2005","October 31, 2005"
47,48,larfus,"247,000","October 5, 2005","October 29, 2005"
48,49,jawed,1,"April 23, 2005","April 23, 2005"

# Q2

In [13]:
driver.get('https://www.bcci.tv/')

In [14]:
nxt=driver.find_element(By.XPATH,"/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
nxt.click()

In [15]:
date_1=driver.find_elements(By.XPATH,'//div[@class="fixture-card-mid d-flex align-items-center justify-content-between"]')

In [16]:
Team=[]

for i in date_1:
    Team.append(i.text.replace('\n',',').replace(',',' '))

In [17]:
Team[0:2]

['India vs Australia', 'India Women vs Pakistan Women']

In [18]:
Series=[]
ser=driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
for i in ser:
    Series.append(i.text)

In [19]:
Series[0:10]

['AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23',
 'ICC WOMENS T20 WORLD CUP 2023',
 'ICC WOMENS T20 WORLD CUP 2023',
 'AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23',
 'ICC WOMENS T20 WORLD CUP 2023',
 'ICC WOMENS T20 WORLD CUP 2023',
 'AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23',
 'AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23',
 'AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23',
 'AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23']

In [20]:
Title=[]
tit=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
for i in tit:
    Title.append(i.text.replace('-',' '))

In [21]:
Title[0:5]

['1st Test  ', '1st T20I  ', '2nd T20I  ', '2nd Test  ', '3rd T20I  ']

In [22]:
Time=[]
time=driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]')
for i in time:
    Time.append(i.text.replace('IST',''))

In [23]:
Ground=[]
place=driver.find_elements(By.XPATH,'//div[@class="fix-place ng-binding ng-scope"]')
for i in place:
    Ground.append(i.text[11:])

In [24]:
Ground[0:5]

['Vidarbha Cricket Association Stadium, Nagpur',
 'Newlands, Cape Town',
 'Newlands, Cape Town',
 'Arun Jaitley Stadium, Delhi',
 "St George's Park, Gqeberha"]

In [25]:
Time[0:5]

['9:30 AM ', '6:30 PM ', '6:30 PM ', '9:30 AM ', '6:30 PM ']

In [26]:
Date=[]
date=driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]')
for i in date:
    Date.append(i.text)

In [27]:
Date[0:5]

['9 FEB 2023', '12 FEB 2023', '15 FEB 2023', '17 FEB 2023', '18 FEB 2023']

In [28]:
table=pd.DataFrame({})
table['Match Title']=Title[:]
table['Series']=Series[:]
table['Teams']=Team[:]
table['Date']=Date[:]
table['Time']=Time[:]
table['Place']=Ground[:]
table

,Match Title,Series,Teams,Date,Time,Place
0,1st Test,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,India vs Australia,9 FEB 2023,9:30 AM,"Vidarbha Cricket Association Stadium, Nagpur"
1,1st T20I,ICC WOMENS T20 WORLD CUP 2023,India Women vs Pakistan Women,12 FEB 2023,6:30 PM,"Newlands, Cape Town"
2,2nd T20I,ICC WOMENS T20 WORLD CUP 2023,India Women vs West Indies Women,15 FEB 2023,6:30 PM,"Newlands, Cape Town"
3,2nd Test,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,India vs Australia,17 FEB 2023,9:30 AM,"Arun Jaitley Stadium, Delhi"
4,3rd T20I,ICC WOMENS T20 WORLD CUP 2023,England Women vs India Women,18 FEB 2023,6:30 PM,"St George's Park, Gqeberha"
5,4th T20I,ICC WOMENS T20 WORLD CUP 2023,India Women vs Ireland Women,20 FEB 2023,6:30 PM,"St George's Park, Gqeberha"
6,3rd Test,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,India vs Australia,1 MAR 2023,9:30 AM,"Himachal Pradesh Cricket Association Stadium, ..."
7,4th Test,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,India vs Australia,9 MAR 2023,9:30 AM,"Narendra Modi Stadium, Ahmedabad"
8,1st ODI,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,India vs Australia,17 MAR 2023,1:30 PM,"ankhede Stadium, Mumbai"
9,2nd ODI,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,India vs Australia,19 MAR 2023,1:30 PM,r YS Rajasekhara Reddy ACA-VDCA Cricket Stadiu...
10,3rd ODI,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,India vs Australia,22 MAR 2023,1:30 PM,"A Chidambaram Stadium, Chennai"

# Q3

In [29]:
driver.get('http://statisticstimes.com/')

In [31]:
nxt=driver.find_elements(By.XPATH,"//div[@class='navbar']/div[2]/div/a[3]")

for i in nxt:
    a=i.get_attribute("href")
    print(a)

https://www.statisticstimes.com/economy/india-statistics.php

In [34]:
driver.get(a)

In [37]:
nxt=driver.find_element(By.XPATH,"//body/div[2]/div[2]/div[2]/ul/li[1]/a")
nxt.click()

In [39]:
data_1=driver.find_elements(By.XPATH,"//div[@id='main']/div[5]/div[1]/div/table/tbody/tr/td")

In [49]:
rank=[]
state=[]
gsdp19=[]
gsdp18=[]
share18=[]
gdp=[]
ogsdp19=[]
ogsdp18=[]
n=1

for i in data_1:
    if n%8==1:
        rank.append(i.text)
    if n%8==2:
        state.append(i.text)
    if n%8==3:
        gsdp19.append(i.text)
    if n%8==4:
        gsdp18.append(i.text)
    if n%8==5:
        share18.append(i.text)
    if n%8==6:
        gdp.append(i.text)
    if n%8==7:
        ogsdp19.append(i.text)
    if n%8==0:
        ogsdp18.append(i.text)
    n=n+1

In [50]:
print(len(rank),len(state),len(gsdp19),len(gsdp18),len(share18),len(gdp),len(ogsdp19),len(ogsdp18))

33 33 33 33 33 33 33 33

In [51]:
table=pd.DataFrame({})
table['Rank']=rank[:]
table['State']=state[:]
table['GSDP 19-20(Cr INR at current prices)']=gsdp19[:]
table['GSDP 18-19(Cr INR at current prices)']=gsdp18[:]
table['Share(18-19)']=share18[:]
table['GDP($ billion)']=gdp[:]
table['GSDP 19-20(Cr INR at 2011-12 prices)']=ogsdp19[:]
table['GSDP 18-19(Cr INR at 2011-12 prices']=ogsdp18[:]
table

,Rank,State,GSDP 19-20(Cr INR at current prices),GSDP 18-19(Cr INR at current prices),Share(18-19),GDP($ billion),GSDP 19-20(Cr INR at 2011-12 prices),GSDP 18-19(Cr INR at 2011-12 prices
0,1,Maharashtra,-,"2,632,792",13.94%,399.921,-,"2,039,074"
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629,"1,312,929","1,215,307"
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726,"1,166,817","1,123,982"
3,4,Gujarat,-,"1,502,899",7.96%,228.290,-,"1,186,379"
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806,"1,156,039","1,091,077"
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556,"793,223","739,525"
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179,"711,627","677,428"
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083,"672,018","621,301"
8,9,Telangana,"969,604","861,031",4.56%,130.791,"663,258","612,828"
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977,"561,801","522,009"
10,11,Kerala,-,"781,653",4.14%,118.733,-,"559,412"
11,12,Delhi,"856,112","774,870",4.10%,117.703,"634,408","590,569"
12,13,Haryana,"831,610","734,163",3.89%,111.519,"572,240","531,085"
13,14,Bihar,"611,804","530,363",2.81%,80.562,"414,977","375,651"
14,15,Punjab,"574,760","526,376",2.79%,79.957,"418,868","397,669"
15,16,Odisha,"521,275","487,805",2.58%,74.098,"396,499","376,877"
16,17,Assam,-,"315,881",1.67%,47.982,-,"234,048"
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187,"243,477","231,182"
18,19,Jharkhand,"328,598","297,204",1.57%,45.145,"240,036","224,986"
19,20,Uttarakhand,-,"245,895",1.30%,37.351,-,"193,273"
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690,-,"112,755"
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369,"124,403","117,851"
22,23,Goa,"80,449","73,170",0.39%,11.115,"63,408","57,787"
23,24,Tripura,"55,984","49,845",0.26%,7.571,"40,583","36,963"
24,25,Chandigarh,-,"42,114",0.22%,6.397,-,"31,192"
25,26,Puducherry,"38,253","34,433",0.18%,5.230,"25,093","23,013"
26,27,Meghalaya,"36,572","33,481",0.18%,5.086,"26,695","24,682"
27,28,Sikkim,"32,496","28,723",0.15%,4.363,"20,017","18,722"
28,29,Manipur,"31,790","27,870",0.15%,4.233,"20,673","19,300"
29,30,Nagaland,-,"27,283",0.14%,4.144,-,"17,647"
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737,-,"16,676"
31,32,Mizoram,"26,503","22,287",0.12%,3.385,"18,797","16,478"
32,33,Andaman & Nicobar Islands,-,-,-,-,-,-

# Q4

In [3]:
driver.get('https://github.com/')

In [4]:
nxt_1=driver.find_elements(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a")
url=[]
for i in nxt_1:
    a=i.get_attribute('href')
    print(a)

https://github.com/trending

In [5]:
driver.get(a)

In [8]:
Language=[]
contri=[]
Descp=[]
Lang=[]
star=[]
Title=[]

In [9]:
repository =driver.find_elements(By.XPATH,"//h1[@class='h3 lh-condensed']/a")
repo_urls=[]
for i in repository[0:30]:
    a=i.get_attribute("href")
    repo_urls.append(a)

for i in repo_urls:

    driver.get(i)

    time.sleep(3)
    #Scraping Languages-
    try:

        cont_tags = driver.find_element(By.XPATH,'//span[@class="color-fg-default text-bold mr-1"]')

        Language.append(cont_tags.text)

    except NoSuchElementException:

        Language.append('-')
    #Scraping Languages-
    try:
        contri_1=driver.find_elements(By.XPATH,"//div[@class='BorderGrid BorderGrid--spacious']/div[5]/div/h2/a/span")
        if len(contri_1)==0:
            contri_2=driver.find_elements(By.XPATH,"//div[@class='BorderGrid BorderGrid--spacious']/div[4]/div/h2/a/span")
        
            if len(contri_2)==1:
                for k in contri_2:
                    contri.append(k.text)
            else:
                contri.append('-')
            
        else:
            for j in contri_1:
                contri.append(j.text)
    except NoSuchElementException:
        contri.append('-')
      
   
      #Scraping Languages-      
    try:
        star_1=driver.find_elements(By.XPATH,'//span[@class="Counter js-social-count"]')
        for i in star_1:
            star.append(i.text)

    except NoSuchElementException:
        star.append('-')
    #Scraping Languages-
    try:
        title=driver.find_elements(By.XPATH,'//div[@class="flex-auto min-width-0 width-fit mr-3"]')
        for i in title:
            Title.append(i.text)
        
    except NoSuchElementException:
        
        Title.append('-')
    try:
        descrip_1=driver.find_element(By.XPATH,'//p[@class="f4 my-3"]')
        Descp.append(descrip_1.text)
    except NoSuchElementException:
        Descp.append('-')

In [10]:
print(len(Title),len(Descp),len(Language),len(contri),len(star))

25 25 25 25 25

In [11]:
table=pd.DataFrame({})
table['Repository Title']=Title[:]
table['Repository Description']=Descp[:]
table['Language Used']=Language[:]
table['Contributors count)']=contri[:]
table['Stars']=star[:]
table

,Repository Title,Repository Description,Language Used,Contributors count),Stars
0,fuergaosi233\n/\nwechat-chatgpt\nPublic,Use ChatGPT On Wechat via wechaty,TypeScript,25,6.9k
1,AutumnWhj\n/\nChatGPT-wechat-bot\nPublic,ChatGPT for wechat https://github.com/AutumnWh...,TypeScript,4,2.2k
2,motion-canvas\n/\nmotion-canvas\nPublic,Visualize Complex Ideas Programmatically,TypeScript,18,5.3k
3,TheAlgorithms\n/\nPython\nPublic,All Algorithms implemented in Python,Python,1,153k
4,djun\n/\nwechatbot\nPublic,为个人微信接入ChatGPT,Go,-,213
5,f\n/\nawesome-chatgpt-prompts\nPublic,This repo includes ChatGPT prompt curation to ...,HTML,-,22.8k
6,Zero6992\n/\nchatGPT-discord-bot\nPublic template,Integrate ChatGPT into your own discord bot,Python,11,1k
7,acikkaynak\n/\ndeprem-yardim-backend\nPublic,afetharita.com backend projesi,Python,16,315
8,samim23\n/\npolymath\nPublic,Convert any music library into a music product...,Python,2,456
9,zhayujie\n/\nchatgpt-on-wechat\nPublic,使用ChatGPT搭建微信聊天机器人，基于OpenAI API和itchat实现。Wecha...,Python,6,1.6k
10,BaRRaKudaRain\n/\nPCem-ROMs\nPublic,This is a collection of requiered ROMs files f...,-,-,471
11,eliaszon\n/\nProgrammers-Overseas-Job-Intervie...,🏂🏻 程序员海外工作/英文面试手册,-,-,1.5k
12,AIGCT\n/\nEASYChatGPT\nPublic,"This is an application project of 'chatgpt',on...",Python,-,209
13,PlexPt\n/\nawesome-chatgpt-prompts-zh\nPublic,ChatGPT 中文调教指南。各种场景使用指南。学习怎么让它听你的话。,-,6,4.7k
14,houko\n/\nwechatgpt\nPublic,wechatgpt golang版 chatgpt机器人(可docker部署)，目前支持微信...,Go,2,309
15,lencx\n/\nChatGPT\nPublic,"🔮 ChatGPT Desktop Application (Mac, Windows an...",Rust,15,11.8k
16,acheong08\n/\nChatGPT\nPublic,Reverse engineered ChatGPT API,Python,55,14.6k
17,openai\n/\nopenai-cookbook\nPublic,Examples and guides for using the OpenAI API,Jupyter Notebook,33,11.8k
18,eatmoreapple\n/\nopenwechat\nPublic,golang微信SDK,Go,,1.7k
19,cezaraugusto\n/\nYou-Dont-Know-JS\nPublic,📗📒 (PT-Br translation) JS Book Series.,JavaScript,,4.8k
20,acikkaynak\n/\ndeprem-yardim-frontend\nPublic,afetharita.com frontend projesi. https://rc.af...,TypeScript,72,654
21,shajen\n/\nrtl-sdr-scanner-cpp\nPublic,-,C++,3,239
22,Fndroid\n/\nclash_for_windows_pkg\nPublic,A Windows/macOS GUI based on Clash,-,3,44.4k
23,kyujin-cho\n/\npixel-volte-patch\nPublic,Rootless replacement for persist.dbg.volte_ava...,Kotlin,2,170
24,acikkaynak\n/\nyardim-agi-flutter\nPublic,"Bu uygulama, ihtiyaç sahibi depremzedelerin ha...",Dart,20,96